# Generated by Django 3.2.9 on 2021-11-13 18:59

from django.db import migrations, models
import tinder.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=tinder.base.services.get_path_upload_avatar),
        ),
    ]
