# Generated by Django 3.2.9 on 2021-11-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_client_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('handpicked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_handpicked', to='tinder.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_owner', to='tinder.client')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
            },
        ),
    ]
